# Generated by Django 3.0.3 on 2020-03-03 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0003_auto_20200221_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchangeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exchanged_currency', models.CharField(max_length=3)),
                ('value_exchanged', models.DecimalField(decimal_places=2, max_digits=12)),
                ('acquired_currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('value2_acquired', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
