# Generated by Django 3.0.3 on 2020-03-05 19:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_currencyexchangemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchangemodel',
            name='value_exchanged',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.1000000000000000055511151231257827021181583404541015625'))]),
        ),
    ]
